# Generated by Django 3.2.15 on 2025-11-04 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('VIII', 'Class VIII'), ('XI', 'Class XI')], max_length=10, unique=True)),
                ('is_open', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FormFieldVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shaheed_status', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True, verbose_name='Shaheed')),
                ('death_type', models.CharField(blank=True, choices=[('in_service', 'In Service Death'), ('war_op', 'Death in War/Op'), ('accidental', 'Accidental Death')], max_length=50, null=True, verbose_name='Type of Death')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('payment_pending', 'Payment Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submission_date', models.DateField(default=django.utils.timezone.now)),
                ('challan_image', models.ImageField(blank=True, null=True, upload_to='challans/')),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('total_fee', models.PositiveIntegerField(default=3000)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='fee_slips/')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('fee_type', models.CharField(default='Single', max_length=20)),
                ('entry', models.CharField(default='8th Class Entry-2026', max_length=100)),
                ('category', models.CharField(blank=True, choices=[('offr_serving', 'Offrs (Serving)'), ('offr_retired', 'Offrs (Retired)'), ('jcos_serving', 'JCOs/Sldrs (Serving)'), ('jcos_retired', 'JCOs/Sldrs (Retired)'), ('caf', 'CAF (FC KPK / Punjab Ranger)'), ('civilian', 'Civilians'), ('fata', 'FATA'), ('balochistan', 'BALOCHISTAN'), ('gilgit', 'Gilgit Baltistan'), ('ajk', 'AJ&K'), ('navy_airforce', 'Personnel of Navy / Airforce')], max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('guardian', models.CharField(max_length=100)),
                ('form_b', models.CharField(blank=True, max_length=50, null=True)),
                ('father_cnic', models.CharField(max_length=15)),
                ('mother_cnic', models.CharField(max_length=15)),
                ('domicile', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('father_occupation', models.CharField(max_length=100)),
                ('army_no', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('is_shaheed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5)),
                ('shaheed_in', models.CharField(blank=True, max_length=100, null=True)),
                ('arm', models.CharField(max_length=50)),
                ('arm_info', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_address', models.TextField()),
                ('mobile_no', models.CharField(max_length=15)),
                ('landline_no', models.CharField(blank=True, max_length=15, null=True)),
                ('test_center', models.CharField(choices=[('Peshawar', 'Peshawar – FG Degree College for Men, School Road, Peshawar Cantt'), ('Abbottabad', 'Abbottabad – Education School, Baloch Centre, Abbottabad'), ('Rawalpindi1', 'Rawalpindi 1 – Military College of Signals, Rawalpindi'), ('Rawalpindi2', 'Rawalpindi 2 – EME College, Rawalpindi'), ('Jhelum', 'Jhelum – Military College Jhelum'), ('Lahore', 'Lahore – Garrison Boys High School (APS Sarfraz Rafiqui Road), Lahore Cantt'), ('Sialkot', 'Sialkot – FG Public High School, Sialkot'), ('Multan', 'Multan – FG Degree College for Boys, Qasim Bela Road, Multan Cantt'), ('Hyderabad', 'Hyderabad – Station Central School / HRDC, Hyderabad'), ('Quetta', 'Quetta – HRDC 33 Div, Khalid Road, Quetta'), ('Karachi', 'Karachi – Garrison HRDC, 5 Corps, Malir Cantt'), ('Sargodha', 'Sargodha – Army Public School, Sargodha'), ('Pano Aqil', 'Pano Aqil – Garrison HRDC, Pano Aqil'), ('Muzaffarabad', 'Muzaffarabad – Garrison HRDC, Muzaffarabad'), ('Gilgit', 'Gilgit – Army Public School, Jutial, Gilgit'), ('Murree', 'Murree – Military College Murree')], max_length=200)),
                ('roll_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('challan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('challan_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
