# Generated by Django 3.2.15 on 2025-11-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='death_type',
        ),
        migrations.AlterField(
            model_name='application',
            name='shaheed_in',
            field=models.CharField(blank=True, choices=[('in_service', 'In Service Death'), ('war_op', 'Death in War/Op'), ('accidental', 'Accidental Death')], max_length=50, null=True, verbose_name='Shaheed In'),
        ),
    ]
