# Generated by Django 3.2.15 on 2025-11-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_auto_20251105_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, choices=[('offr_serving', 'Offrs (Serving)'), ('offr_retired', 'Offrs (Retired)'), ('offr_isd', 'Offrs (In Service Death)'), ('offr_shaheed', 'Offrs (Shaheed)'), ('jcos_serving', 'JCOs/Sldrs (Serving)'), ('jcos_retired', 'JCOs/Sldrs (Retired)'), ('jcos_isd', 'JCOs/Sldrs (In Service Death)'), ('jcos_shaheed', 'JCOs/Sldrs (Shaheed)'), ('caf', 'CAF (FC KPK / Punjab Ranger)'), ('civilian', 'Civilians'), ('fata', 'FATA'), ('balochistan', 'BALOCHISTAN'), ('gilgit', 'Gilgit Baltistan'), ('ajk', 'AJ&K'), ('navy_airforce', 'Personnel of Navy / Airforce')], max_length=50, null=True),
        ),
    ]
