# Generated by Django 3.2.15 on 2025-11-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_alter_application_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='roll_slip',
            field=models.FileField(blank=True, null=True, upload_to='roll_slips/'),
        ),
    ]
