# Generated by Django 3.2.15 on 2025-11-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_application_roll_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='secure_token',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
