# Generated by Django 3.2.15 on 2025-11-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_application_secure_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-submission_date'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['roll_number'], name='admissions__roll_nu_03c861_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='admissions__status_cd8e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['category'], name='admissions__categor_3e21d6_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['test_center'], name='admissions__test_ce_45ec1f_idx'),
        ),
    ]
