# Generated by Django 5.2.8 on 2025-11-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_messagetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='marksheet_10th',
            field=models.FileField(blank=True, null=True, upload_to='xi/marksheets/10th/', verbose_name='10th Class Marksheet'),
        ),
        migrations.AddField(
            model_name='application',
            name='marksheet_9th',
            field=models.FileField(blank=True, null=True, upload_to='xi/marksheets/9th/', verbose_name='9th Class Marksheet'),
        ),
        migrations.AddField(
            model_name='application',
            name='percentage_10th',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='10th Class Percentage'),
        ),
        migrations.AddField(
            model_name='application',
            name='percentage_9th',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='9th Class Percentage'),
        ),
    ]
