# Generated by Django 5.2.8 on 2025-11-15 04:33

import admissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_application_marksheet_10th_application_marksheet_9th_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='class_name',
            field=models.CharField(choices=[('VIII', 'Class VIII'), ('XI', 'Class XI')], default='VIII', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='arm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='marksheet_10th',
            field=models.FileField(blank=True, null=True, upload_to='xi/marksheets/10th/', validators=[admissions.models.validate_marksheet], verbose_name='10th Class Marksheet'),
        ),
        migrations.AlterField(
            model_name='application',
            name='marksheet_9th',
            field=models.FileField(blank=True, null=True, upload_to='xi/marksheets/9th/', validators=[admissions.models.validate_marksheet], verbose_name='9th Class Marksheet'),
        ),
    ]
