# Generated by Django 5.2.8 on 2025-11-16 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_application_class_name_alter_application_arm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('VIII', '8th Class'), ('XI', '11th Class')], max_length=10, unique=True)),
                ('normal_deadline', models.DateField(help_text='Last date for normal fee')),
                ('late_deadline', models.DateField(help_text='Start of late/double fee (inclusive)')),
                ('final_deadline', models.DateField(help_text='Start of final/triple fee (inclusive)')),
                ('stop_after_final', models.BooleanField(default=True)),
                ('base_fee', models.PositiveIntegerField(default=0, help_text='Normal fee (flat)')),
                ('double_fee', models.PositiveIntegerField(default=0, help_text='Double fee (flat)')),
                ('triple_fee', models.PositiveIntegerField(default=0, help_text='Triple fee (flat)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fee Config',
                'verbose_name_plural': 'Fee Configs',
                'ordering': ['class_name'],
            },
        ),
        migrations.CreateModel(
            name='FeeCategoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Use values from Application.CATEGORY choices', max_length=100)),
                ('normal_fee', models.PositiveIntegerField(default=0)),
                ('late_fee', models.PositiveIntegerField(default=0)),
                ('final_fee', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_fees', to='admissions.feeconfig')),
            ],
            options={
                'verbose_name': 'Fee Category Config',
                'verbose_name_plural': 'Fee Category Configs',
                'ordering': ['fee_config', 'category'],
                'unique_together': {('fee_config', 'category')},
            },
        ),
    ]
