# Generated by Django 5.2.8 on 2025-11-18 05:47

import admissions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_feeconfig_feecategoryconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', validators=[admissions.models.validate_photo]),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user'], name='admissions__user_id_90e743_idx'),
        ),
    ]
